name: CD

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar GCC
        run: sudo apt update && sudo apt install gcc -y

      - name: Compilar binário
        run: gcc main.c -o biblioteca

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: programa-biblioteca
          path: biblioteca
