name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar GCC
        run: sudo apt update && sudo apt install gcc -y

      - name: Compilar projeto
        run: gcc main.c -o biblioteca

      - name: Testar compilação
        run: ls -la
